Add FAQs and list of good practices
idmc-labs/idmc-website-components pull request #5
Opened 2022-05-24 05:50 UTC by barshathakuri

- Addresses XXX
- Depends on #develop

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

2022-05-24 11:07 UTC, AdityaKhatri requested changes

2022-05-24 11:07 UTC, AdityaKhatri commented on app/views/GoodPractices/index.tsx
>                          </CollapsibleContent>
Use list view

2022-05-24 11:07 UTC, AdityaKhatri commented on app/views/GoodPractices/index.tsx
> +                                </section>
use listview

2022-06-10 06:01 UTC, frozenhelium approved these changes

2022-06-10 06:05 UTC, frozenhelium approved these changes

2022-06-10 06:08 UTC, merged