Feature/add gidd page
idmc-labs/idmc-website-components pull request #57
Opened 2023-04-26 04:56 UTC by AdityaKhatri

## Changes

* Add GIDD Page

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2023-04-26 08:10 UTC, tnagorra requested changes

2023-04-26 08:10 UTC, tnagorra commented on app/components/ProgressLine/index.tsx
> +    const progress = ((value ?? 0) / (total ?? 0)) * 100;
The total should never be zero

2023-04-26 08:10 UTC, tnagorra commented on app/components/ProgressLine/index.tsx
> +    const progressWidth = `${bound(isDefined(progress) ? progress : 0, 0, 100)}%`;
The progress will always be defined because of default value

2023-04-26 08:10 UTC, tnagorra commented on app/components/ProgressLine/styles.css
> +        background-color: #f0f0f0;
Let's not hardcode values

2023-04-26 08:10 UTC, tnagorra commented on app/components/tableHelpers/Status/index.tsx
> +import React from 'react';
Why do we need this?

2023-04-26 08:10 UTC, tnagorra commented on app/utils/common.ts
> +    return sum(newArgs) === 0 ? undefined : sum(newArgs);
Why call sum twice?

2023-04-26 08:31 UTC, AdityaKhatri commented on app/Base/styles.css
> +    --tui-radius-border-large: 0.8rem;
Nope, this doesn't exist yet

2023-04-29 12:32 UTC, tnagorra commented on app/views/Gidd/index.tsx
> +                    (item) => roundAndRemoveZero(item.newDisplacement ?? undefined),
We need to check where we are using roundAndRemoveZero.
Why not use this on the other tables? Does the server do it for us?

2023-04-29 12:33 UTC, tnagorra commented on app/utils/common.ts
> +export function add(args: (number | undefined)[]) {
```suggestion
export function sumAndRemoveZero(args: (number | undefined)[]) {
```

2023-04-29 12:36 UTC, tnagorra commented on app/views/Gidd/index.tsx
> +                    (item) => roundAndRemoveZero(item.newDisplacement ?? undefined),
In the server, it's done on the exports.


We may need to use this on the aggregated table as well.

2023-05-02 13:17 UTC, tnagorra requested changes

2023-05-02 13:17 UTC, tnagorra commented on app/views/Gidd/EventTitle/Modal/index.tsx
> +const hazardKeySelector = (item: Country) => item?.iso3 ?? '';
What?

2023-05-02 13:17 UTC, tnagorra commented on app/views/Gidd/EventTitle/Modal/index.tsx
> +        eventId,
Let's also pass release environment here

2023-05-02 13:17 UTC, tnagorra commented on app/views/Gidd/index.tsx
> +        disasterStats?.displacementsByHazardType?.sort(
Let's not sort directly

2023-05-02 13:17 UTC, tnagorra commented on app/views/Gidd/index.tsx
> +                                    variant="primary"
Let's disable

2023-05-02 14:30 UTC, merged