Make country profile charts responsive
idmc-labs/idmc-website-components pull request #7
Opened 2022-06-14 06:34 UTC by barshathakuri

- Addresses XXX
- Depends on XXX

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

2022-06-16 06:46 UTC, tnagorra requested changes
Please do not commit package-lock.json. We already use yarn.lock to track installed dependencies.

2022-06-16 06:46 UTC, tnagorra commented on package.json
>          "@the-deep/deep-ui": "^2.0.0-beta.0",
Let's remove deep ui

2022-06-16 06:46 UTC, tnagorra commented on app/views/GoodPractices/styles.css
> +
Please remove this whitespace

2022-06-16 06:46 UTC, tnagorra commented on app/views/GoodPractices/index.tsx
> +                                    )}
the filtered empty message should be different than empty message

2022-06-16 06:46 UTC, tnagorra commented on app/Base/index.tsx
>  import '@the-deep/deep-ui/build/esm/index.css';
Let's remove all dependencies from deep ui

2022-06-16 06:46 UTC, tnagorra commented on app/components/SliderInput/styles.css
> +    margin-top: var(--dui-spacing-medium);
Why add a margin top?

2022-06-16 06:46 UTC, tnagorra commented on app/views/CountryProfile/styles.css
> +        }
Why add asymmetric margin and padding?

2022-06-16 06:46 UTC, tnagorra commented on app/views/CountryProfile/index.tsx
> +                <div className={styles.timeRangeContainer}>
Any reason to add a container here?

2022-06-16 06:46 UTC, tnagorra commented on app/views/CountryProfile/index.tsx
> +                <div className={styles.timeRangeContainer}>
Any reason to add a container here?

2022-06-17 10:51 UTC, tnagorra requested changes

2022-06-17 10:51 UTC, tnagorra commented on app/views/CountryProfile/index.tsx
> -                    <div />
We shouldn't remove this

2022-06-17 10:51 UTC, tnagorra commented on app/views/GoodPractices/index.tsx
> +    console.warn('list', goodPracticeList);
Let's remove the console

2022-06-21 10:42 UTC, tnagorra requested changes

2022-06-21 10:42 UTC, tnagorra commented on app/components/GoodPracticeItem/index.tsx
> +            )} */}
Let's just remove this block

2022-06-21 10:42 UTC, tnagorra commented on app/views/GoodPractices/index.tsx
> +                                            No Good Practice Found
No result found.

2022-06-21 10:42 UTC, tnagorra commented on app/views/GoodPractices/index.tsx
> +                                            No Filtered Good Practice Found
No result found for your filtering criteria.

2022-06-27 06:01 UTC, frozenhelium approved these changes

2022-06-29 06:00 UTC, merged